Объекты и массивы, основы тестирования
js-tasks-ru/js-20210126_sergey023 pull request #3
Opened 2021-02-02 23:40 UTC by Serhii7

2021-02-02 23:46 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2021-02-04 13:44 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        const pathArr = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-02-04 13:44 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        let value = obj;
good 👍 , да в данном случае `value` это `let`

2021-02-04 13:51 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +            if (item in value) {
помните мы говорили про то что не следует использовать `in` для проверки наличия свойства в объекте, так как у него есть побочный эффект - он проверяет наличие как собственных так и унаследованных свойств.
Попробуйте выполнить вот такую проверку:
```
'toString' in {}
```

2021-02-04 13:52 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return Array.from(new Set(arr));
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2021-02-04 13:53 UTC, dosandk requested changes
необходимо внести правки в решение `createGetter`

2021-02-05 14:05 UTC, dosandk approved these changes

2021-02-05 14:05 UTC, merged